[package]
name = "riptide-native-modules"
version = "0.2.0"
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]
description = "Native module support for Riptide"

[dependencies]
libloading = "0.5"

[dependencies.riptide]
path = "../riptide"
