[package]
name = "riptide-shell"
version = "0.2.0"
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]
description = "RipShell"
edition = "2018"

[dependencies]
clipboard = "0.5"
directories = "2.0"
exitcode = "1.1"
futures-preview = "0.3.0-alpha.18"
structopt = "0.3"
termion = "1.5"
# For parsing user input
vte = "0.3"

[dependencies.log]
version = "0.4"
features = ["std"]

[dependencies.log-panics]
version = "2.0"
features = ["with-backtrace"]

[dependencies.riptide-runtime]
path = "../runtime"
