[package]
name = "riptide-shell"
version = "0.2.0"
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]
description = "RipShell"
edition = "2018"

[dependencies]
clogger = "0.1"
log = "0.4"
structopt = "0.2"
termion = "1.5"

[dependencies.riptide]
path = "../riptide"
