[package]
name = "riptide-shell"
version = "0.2.0"
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]
description = "RipShell"

[dependencies]
lazy_static = "1.0"
termion = "1.5"

[dependencies.riptide]
path = "../riptide"
