[package]
name = "riptide"
version = "0.1.0"
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]
description = "The Riptide shell"

[[bin]]
name = "riptide"
path = "main.rs"

[dependencies]
lazy_static = "0.2"
nix = "0.8.1"
ripflow = { path = "../ripflow" }
termion = "1.3"
utf8parse = "0.1.0"
