[package]
name = "riptide-syntax"
version = "0.2.0"
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]
description = "The Riptide language parser"

[dependencies]
log = "0.4"

[dev-dependencies]
difference = "2.0"
glob = "0.2"
minidom = "0.9"
stderrlog = "0.3"
toml = "0.4"

[dev-dependencies.riptide-syntax-extra]
path = "../syntax-extra"
