[package]
name = "riptide-syntax"
version = "0.2.0"
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]
description = "The Riptide language parser"

[dependencies]
pest = "^1.0"
pest_derive = "^1.0"

[dev-dependencies]
difference = "2.0"
glob = "0.2"
log = "0.4"
stderrlog = "0.3"
toml = "0.4"
