[package]
name = "riptide-syntax-extra"
version = "0.2.0"
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]
description = "Riptide language parser extras"

[dependencies]
log = "0.4"
minidom = "0.9"
quick-xml = "0.12"

[dependencies.riptide-syntax]
path = "../syntax"
