[package]
name = "ripflow"
version = "0.2.0"
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]
description = "The Ripflow language interpreter"

[lib]
name = "ripflow"
path = "lib.rs"

[dependencies]
lazy_static = "0.2"
nix = "0.8.1"
termion = "1.3"
utf8parse = "0.1.0"
