[package]
name = "riptide"
version = "0.2.0"
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]
description = "The Riptide language interpreter"

[dependencies]
nix = "0.8.1"

[dependencies.riptide-syntax]
path = "../syntax"
